apiVersion: v1
kind: ConfigMap
metadata:
  name: conjur-connect
  namespace: starai-mongo
data:
  CONJUR_APPLIANCE_URL: "https://aruntenant.secretsmgr.cyberark.cloud"
  CONJUR_ACCOUNT: "conjur"
  CONJUR_AUTHN_URL: "https://aruntenant.secretsmgr.cyberark.cloud/authn-k8s/Arun-MIM"
